#Configuration for Travis CI build


language: java

jdk:
  - oraclejdk8
#  - openjdk6

install:
  - IDEA_VERSION=14.0.3
  - IDEA_TAR=ideaIC-${IDEA_VERSION}.tar.gz
  - |
    if [ -f ~/$IDEA_TAR ]; then
        echo "Copying existing IDEA archive."
        cp ~/$IDEA_TAR .
    else
        echo "Downloading IDEA archive."
        travis_retry wget http://download.jetbrains.com/idea/$IDEA_TAR -P ~
        echo "Copying IDEA archive."
        cp ~/$IDEA_TAR .
    fi
  - echo "Removing existing IDEA installation."
  - rm -rf idea-IC-*
  - echo "Installing IDEA to idea-IC/"
  - tar zxf $IDEA_TAR
  - rm -rf $IDEA_TAR
  - mv idea-IC-* idea-IC
  - echo "Creating build.properties file for ant."
  - echo "idea.home=$(pwd)/idea-IC" > build.properties
  - echo "jdk.home.1.8=$JAVA_HOME" >> build.properties
  - cat build.properties
  - travis encrypt DEPLOY_KEY="a2:03:d6:08:13:fa:22:9e:c7:cc:f6:9a:bd:37:ec:cf" --add env.matrix
  - cat travis/deploy_key.pem

script: ant