language: java
branches:
  only:
    - master
jdk:
- oraclejdk8
notifications:
  email: false
install:
- IDEA_VERSION=14.0.3
- IDEA_TAR=ideaIC-${IDEA_VERSION}.tar.gz
- ! "if [ -f ~/$IDEA_TAR ]; then\n    echo \"Copying existing IDEA archive.\"\n    cp
  ~/$IDEA_TAR .\nelse\n    echo \"Downloading IDEA archive.\"\n    travis_retry wget
  http://download.jetbrains.com/idea/$IDEA_TAR -P ~\n    echo \"Copying IDEA archive.\"\n
  \   cp ~/$IDEA_TAR .\nfi\n"
- echo "Removing existing IDEA installation."
- rm -rf idea-IC-*
- echo "Installing IDEA to idea-IC/"
- tar zxf $IDEA_TAR
- rm -rf $IDEA_TAR
- mv idea-IC-* idea-IC
- echo "Creating build.properties file for ant."
- echo "idea.home=$(pwd)/idea-IC" > build.properties
- echo "jdk.home.1.8=$JAVA_HOME" >> build.properties
after_success:
- git remote add deploy LHulk@github.com/LHulk/SOPRA
script: ant
